I add to the array but haven't attempted to render it to the screen. However after adding one i can see it in  console.log second add breaks into a uncaught TypeError state.push is not a function